### PR TITLE
SR2023 layout

### LINKED ISSUE #986: Prepare a layout of the competition
This will need to specify where the arenas, team pits, reception, helpdesk and so forth are.
The outcome from this task should be an entry in https://github.com/srobo/comp-floorplans.

### Original

[comp/venue/layout](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout.yaml)

### Dependencies

 * #985 Get fire plans from the venue

### PR DESCRIPTION
**Pull request by WillB97**
Venue_Map
Venue_Tech_Map

Fixes https://github.com/srobo/tasks/issues/986

### CODE REVIEW

**Comment by trickeydan** [comment]
I'm really quite uncomfortable about the Photo Booth being behind helpdesk. This will make keeping competitors out of the way even more difficult. Last year it was really important for us to have a proper rope barrier so that helpdesk volunteers were not pestered. 

Have you considering placing it behind SUSU reception instead?

Alternatively, could we swap it around so that the Photo Booth is in front of both first aid and helpdesk so we can maintain a volunteer only area?

**Comment by sedders123** [comment]
I don't think we considered behind SUSU reception but that is an interesting idea. That would be in a walk way though and not sure how that fits into fire plans (and could block the goods lift).

The photo booth should be empty for most of the event, teams will be chaperoned there, have their photo taken and then they'll go back to their pits. It's not meant to be a place for anyone to hang out.

Keen to understand how teams could pester help desk, I thought help desk is where we wanted teams with issues to go? Were team's just hanging around after issues were resolved?

We've asked for the Clubs and Socs room Fri-Sun so we can have a volunteer only area :)

**Comment by trickeydan** [comment]
> Keen to understand how teams could pester help desk, I thought help desk is where we wanted teams with issues to go?

Yes, but we operate a queue usually. I don't believe we can operate a functional helpdesk if we are surrounded on all sides, and are having to supervise students to stop them swapping out batteries themselves etc. 

This isn't an area for volunteers to relax, it's a working area. The same issues would present if we allowed unsupervised competitors into tech desk.

Please _please_ consider other options.

**Comment by trickeydan** [comment]
> teams will be chaperoned there

Do we have volunteer capacity? Last few years I don't think we've done this, teams were told to turn up in a given slot.

**Comment by sedders123** [comment]
I'm not sure there's anywhere else we could put the photo booth. Looking at the floor plans, I think with the limited space behind SUSU reception it would be tricky to fit the teams in and get the camera far enough away for a good photo. I have spent some time trying to find somewhere that's not in a walkway, is large enough, and has adequate lighting we could use instead and I can't find one (though open to suggestions from others!).

Looking at last years volunteer schedule we did have a 'Photo Studio Assistant' who was meant to chaperone teams. And even if we didn't have a dedicated assistant the photographer could fetch teams themselves (Jamie did end up doing this last year). As the photo booth is behind the rope barrier, teams would be escorted in and out by either the photographer or an assistant meaning help desk volunteers shouldn't have to supervise them.

Is a guaranteed chaperone while behind the rope barrier enough to reduce your concerns?

**Comment by Tyler-Ward** [comment]
From the photography side I think a two stage photo booth system could work, It would be useful to have a third person assigned to the busy photo period so we have the photographer at the photo booth, someone managing teams by the waiting area (checking that they have all arrived and making sure they don't block the routes between the café and the cube and the helpdesk help point and the rest of the venue), and another person free to gather teams. This can then be reduced to two when we get to the point where there are only a few teams to chase down as the photographer can manage teams and then take the photos. if we go down this route we should also have some signage for the photo waiting area. Alternatively we could use the shepherds to gather teams and have "fixed*" photo slots for teams in the schedule (we had some success with the shepherds doing this last year when taking the final photos for the last few teams so could expand to the entire event). *we should probably still try and grab teams later if they miss their slots.

As well as helpdesk it should also be noted that we probably want to keep that area somewhat clear so it isn't two crowded near the first aid desk.

**Comment by Tyler-Ward** [comment]
Some other venue thoughts:

- Re photo booth placement are we unable to place it in its usual location by the bridge?
- Also on L2 I assume we are fine to have team pits in front of the fire exit next to the cube, (do we need to be concerned about them having things scattered around their area that may get in the way of the route out?)
- As we don't need to do media consent we might be able to reduce the size of reception given it needs to do a lot less.
- The power tool area appears to be outside. I assume there is a gazebo there or similar now or do we have an alternative plan if there is bad weather.

**Comment by trickeydan** [comment]
> Is a guaranteed chaperone while behind the rope barrier enough to reduce your concerns?

I guess. Not ideal.

I've also noticed that we'll want the rope barrier at the other end of helpdesk as it is in the current map. I don't mind if this isn't updated though as we'll just move it when we set up helpdesk. Helpdesk plans are still in the works and we don't yet have written up docs or info available.

**Comment by sedders123** [comment]
> Re photo booth placement are we unable to place it in its usual location by the bridge?

Unfortunately the Bridge will be open so we can't block the entrance.

> Also on L2 I assume we are fine to have team pits in front of the fire exit next to the cube, (do we need to be concerned about them having things scattered around their area that may get in the way of the route out?)

The venue rules say that walkways must be kept clear and we'll have roving helpers and/or shepherds remind teams of this if needed.

> As we don't need to do media consent we might be able to reduce the size of reception given it needs to do a lot less.

We still need to collect in batteries and give out swag. Once teams have arrived we could reduce but having more teams being processed in parallel speeds things up considerably on the Saturday morning.

> The power tool area appears to be outside. I assume there is a gazebo there or similar now or do we have an alternative plan if there is bad weather.

SUSU apparently have a cover for this area, we're making sure we have use of this

**Comment by Scarzy** [comment]
Is the photo booth fully enclosed?

If so, can it perform the secondary role of being the private first aid area if something happens?
Alternatively, we will probably need the volunteer area for this as per previous years. (I vaguely recall last year the first aider was hoping to use the room behind that door for the private area, but that door now looks blocked off)

**Comment by WillB97** [comment]
> Is the photo booth fully enclosed?

No, it's just a plain backdrop like last year. The intention was to use the volunteer area as a private first aid area, same as last year.

**Review by Adimote — APPROVED** [review]

**Review by RealOrangeOne — APPROVED** [review]
On the assumption it's known that `map.svg` isn't up-to-date (team pit locations, photo booth, power tools), I think this looks great. I suggest we get this in, and any other minor changes be separate iterations.

**Comment by WillB97** [comment]
Yes, we were waiting on an agreed layout before updating `map.svg`

**Pull request merged**
