### PR TITLE
Revert "Move battery charging from stage to helpdesk"

### PR DESCRIPTION
**Pull request by trickeydan**
This reverts commit c253f5fd971a99352f84832d9c36c2c9f352c666.

See conversation below the merge in #6. There is not enough space to put battery charging there.

There was talk of moving battery charging to the volunteer area, but for now I'd like to move it back to the known good location.

### CODE REVIEW

**Review by RealOrangeOne — CHANGES_REQUESTED** [review]
I don't think this is the right change to be made. Moving it here is a large improvement, and is only 1 table less than the stage location which this restores. There's no reason we can't add in another table or 2 to the back side to account for the extra batteries.

**Comment by WillB97** [comment]
The suggestion was made to put the chargers on level 3. This seems like a far better solution as it both allows for more space and keeps battery charging away from the competitors. 

Level 2 is already the busiest floor, so moving the charging around on level 2 does not relieve the space problem, it simply makes it effect someone else. 

Also adding more tables to the helpdesk will significantly restrict the walkway past the pits.

**Comment by RealOrangeOne** [comment]
There are now discussions happening in Slack (which will likely end up in a ticket at some point) regarding where battery charging will go. For now, I don't think it's useful to have this PR open, as it's highly unlikely the position this PR implements will be the final.

**Comment by trickeydan** [comment]
In the future, can you not close my pull requests until I've had a chance to respond please. It's slightly offensive.

**Pull request closed without merging**
