### PR TITLE
Update team pits locations and numbering

### PR DESCRIPTION
**Pull request by sedders123**
Updated to match comments from https://github.com/srobo/tasks/issues/211#issuecomment-475876141

### CODE REVIEW

**Review by Tyler-Ward — CHANGES_REQUESTED** [review]
Looks good, the team power requirements on L2 should be updated to reflect the removal of pit 7

**Review by Tyler-Ward — APPROVED** [review]
Looks good to me

**Comment by Tyler-Ward** [comment]
Team TLA to pit information will be added to this pull request as well

**Comment by Tyler-Ward** [comment]
All looks good to me

**Comment by WillB97** [comment]
Since the team_names.txt has been updated the build script should be re-run to update the output folder

**Pull request merged**
