### PR TITLE
Move battery charging from stage to helpdesk

### PR DESCRIPTION
**Pull request by RealOrangeOne**
As was raised in https://github.com/srobo/tasks/issues/64#issuecomment-469062409, battery charging on the stage might get annoying, and clutters it slightly. Instead, we can move it to help desk, and extend it a little.

### CODE REVIEW

**Review by Tyler-Ward — APPROVED** [review]
Looks good to me

**Comment by WillB97** [comment]
Looks good

**Review by WillB97 — APPROVED** [review]

**Comment by WillB97** [comment]
That will be on a moderately long power run but that shouldn't be an issue.

**Comment by PeterJCLaw** [comment]
I'm sure this has been considered, but just to double check: is there enough space at Helpdesk to actually do this without it getting in the way of other things?

At Newbury (admittedly 50 teams rather than 30), this took a bank of desks about 10m long (estimate based on having a quick look at a floorplan from 2017 and the desks in question occupying most of a wall labelled as being 12.7m long) . I would expect we'll need a proportionately similar amount of space -- in the region of 6m length.

**Comment by mildlyincompetent** [comment]
The current location of the helpdesk does not seem to allow space for battery charging unless we put battery charging in the corridor between the cube doors and the rear fire exit, and I'm not convinced that's a wise idea.

**Comment by trickeydan** [comment]
I agree with both @PeterJCLaw and @mildlyincompetent here. There is not enough space, either for the batteries to be charged, or for fire escape. I also suspect that it will be somewhat cramped.

There was talk the other day of moving the battery charging to the volunteer area, but for now I am going to open a PR to revert this as I do not believe the benefits of this layout outweigh the cons compared to the previous layout.

**Comment by RealOrangeOne** [comment]
If we are worried about table room, let's just add some more tables.

Now that this PR is merged, I don't think this is the right place to comment on it. I'd suggest opening an issue to track this requested change so we can discuss it properly.

**Pull request merged**
