### PR TITLE
Add map for 2022 venue

### PR DESCRIPTION
**Pull request by sedders123**
This is the map used in the 2022 competition booklet

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
Reviewers: For reference, last year's map: https://github.com/srobo/event-maps-2019/blob/master/maps.svg

**Comment by RealOrangeOne** [comment]
Thought: My understanding is that there's a disabled toilet at the end of bar 3. Should we flag that on the map?

**Review by trickeydan — DISMISSED** [review]
The icon for the accessible toilet on L4 is in the wrong place. It should be in an alcove the other side of the doors. It definitely is not that side of the lift.

See [L4.svg](https://github.com/srobo/comp-floorplans/blob/master/2022/templates/L4.svg)

**Comment by antoinepetty** [comment]
We need to remove TLC as they've dropped out

**Comment by WillB97** [comment]
> The icon for the accessible toilet on L4 is in the wrong place. It should be in an alcove the other side of the doors. It definitely is not that side of the lift.

It would be good if we could make it clear that they are accessed of the concourse, not through the doors to the lift.

**Comment by sedders123** [comment]
@trickeydan @WillB97 Could you please check the new location of the accessible toilet. Also if there is an accessible toilet on L3 as Jake suggests could someone please indicate where the icon should go. Thanks :)

**Review by WillB97 — APPROVED** [review]
That location is fine. I would advise against marking the disabled toilet on L3 since it's well into the blueshirt-only area and rather small, certainly from where the competitors are the one on L4 is much easier to get to.

**Review by RealOrangeOne — APPROVED** [review]
Worth reviewing table locations based on the latest team numbers, but overall this looks great!

**Review by PeterJCLaw — CHANGES_REQUESTED** [review]
- HSO and TLC have dropped out -- we should remove them
- CLY are not mentioned in the key (but should be)

**Pull request merged**
