### PR TITLE
SR2020 floorplans

### PR DESCRIPTION
**Pull request by WillB97**
The Student Robotics 2020 competition floorplans.
Currently has the floorplanning for the major blocks, once the placement of these is agreed they can be elaborated to the specific components needed for each and power can be laid out.

Opened to allow collaboration on designs, see srobo/tasks#421 and srobo/tasks#474.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Thanks for putting this together :)

If I'm reading this right, I think there's space for only 30 teams at the moment, yet we're likely to need more than that (we've 36 teams currently I think). Is this intentional and/or what are the limitations on adding more pit spaces?
I think we could get another four in the space in the lower right room (next to the four currently in a line on their own). Not sure where to put the remaining two though.

**Comment by WillB97** [comment]
The current pit layout was just to get a rough idea of the space.

We are currently planning on having 35 pits and think these will fit. Pits already needed rearrangement to move them against the walls and clear access to firedoors.

We also discussed changing the placement of both staging and tech deck. We considered having staging on the south side of the arena with tech desk either behind it or in the south-east of the room depending on available space. This leaves 3 arena side for spectators. Further discussion is needed on how much tech desk actually needs to be able to see the arena.

Reception was also suggested to be with power tools outside or on the unused stage inside.
We also need to find a location for a practice arena.

**Comment by WillB97** [comment]
The plans should now contain:
- All the pits
- All the tables
- The installed and SR provided screens

I still need to add:
- The power requirements
- The network and hdmi cabling
- Arena props

**Comment by sedders123** [comment]
Is sticking the first aid station next to team pits ok? I imagine ideally they'd need somewhere that is relatively quiet and that can provide a reasonable level of privacy. cc @Scarzy as Health and Safety coordinator

**Comment by WillB97** [comment]
Reading have movable screens that we were intending to put around the first aid area

**Comment by Scarzy** [comment]
This was discussed on the day. The screens seem like a good solution.
Unlike Southampton, Reading doesn't seem to have as many little spaces that
we could use for it, so in the main space just shielded off does seem to be
the best approach.

Incidentally, we can always move the screens to the casualty should it
prove necessary, which is an advantage.

**Review by Adimote — APPROVED** [review]
rubber stamping for posterity

**Comment by Adimote** [comment]
#YOLO

**Pull request merged**
