### PR TITLE
Remove dropped-out teams to simplify map

### PR DESCRIPTION
**Pull request by HarryCutts**

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
@HarryCutts just checking you've seen that this is failing CI?

**Comment by HarryCutts** [comment]
Yes, just haven't had the chance to debug

**Comment by HarryCutts** [comment]
Has now passed (I managed to amend a commit without actually adding the fix)

**Comment by PeterJCLaw** [comment]
@HarryCutts I think we can also remove "KAA".

**Comment by PeterJCLaw** [comment]
oh, and EWS

**Comment by HarryCutts** [comment]
Done

**Review by PeterJCLaw — APPROVED** [review]

**Pull request merged**
