### PR TITLE
Update staging area with new layout

### PR DESCRIPTION
**Pull request by RealOrangeOne**
We modified the staging area slightly to account for foot traffic through the entrance, and for teams to watch their robot from the staging area nicely. 

Primary changes:
- Split incoming and outgoing areas
- Add more tables to staging to match number of teams
	- 4 x ~50cm robots won't fit on 1 table
- Bring scoring desk forwards
	- Move it away from the wall so they can at least see what's going on, and _maybe_ not block stairs
- Move head shepherding display onto scoring table
- Update power / network requirements to match
- Extend staging area slightly to account for changes

The scoring table is placed with a guess. We may need to adjust this depending on where the stairs actually are.

Screenshot, because reviewing on GitHub can be annoying:

image

### CODE REVIEW

**Review by Tyler-Ward — CHANGES_REQUESTED** [review]
Some edits.
* The changes to the cube also want to be made to L2.
* the location of the score entry desk will be in the way of the stairs as they are inset from the edge of the stage (could place against the wall or place on the stage in the thinner end section),

**Comment by RealOrangeOne** [comment]
> the location of the score entry desk will be in the way of the stairs

I was quite worried about this when designing it, hence the note about flexible location. Although, now I look at the finished item, there isn't a real need to move the table, since I extended the barrier down. Will adjust :+1:

**Comment by WillB97** [comment]
Just an FYI, the tables used in the floorplan are 1.5m but the tables ordered are 6ft(i.e. 1.8m).

**Comment by RealOrangeOne** [comment]
> The changes to the cube also want to be made to L2.

I elected to remove the layout from the L2 plans, because it's unnecessary duplication as we have a dedicated plan.

**Comment by RealOrangeOne** [comment]
> the tables used in the floorplan are 1.5m but the tables ordered are 6ft(i.e. 1.8m).

That's unfortunate, but by the looks of things there's still plenty of room. Worst comes to worst we can extend the lower battier down even further, but that's likely unnecessary.

**Review by sedders123 — APPROVED** [review]
LGTM 👍  (after conflicts sorted)

**Review by Tyler-Ward — APPROVED** [review]
All looks good to me

**Pull request merged**
